<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Chitti_Surf" failures="1" tests="2" name="myTestRunner.TestRunner" time="76.422" errors="0" timestamp="2025-01-31T15:07:15 CST" skipped="0">
  <testcase classname="myTestRunner.TestRunner" name="runScenario" time="37.299"/>
  <testcase classname="myTestRunner.TestRunner" name="runScenario" time="39.123">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at org.testng.Assert.assertFalse(Assert.java:89)
at stepDefinitions.SubmitOrderStepDef.verify_confirmationmsg(SubmitOrderStepDef.java:105)
at âœ½.verify the confirmation message order deleted succefully is diplayed(file:///C:/Users/hemaj/eclipse-workspace/CuCumberBDDMaveProject/src/test/java/bddcucumber/SubmitOrder.feature:21)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- myTestRunner.TestRunner -->
